import { supabase } from '../supabaseClient';

/**
 * Budget Service - Handles all database operations for budget entries
 */

// Fetch all entries ordered by date_created (newest first)
export const getAllEntries = async () => {
  try {
    const { data, error } = await supabase
      .from('budget_entries')
      .select('*')
      .order('date_created', { ascending: false });

    if (error) throw error;
    return { data, error: null };
  } catch (error) {
    console.error('Error fetching entries:', error);
    return { data: null, error };
  }
};

// Fetch only income entries
export const getIncomeEntries = async () => {
  try {
    const { data, error } = await supabase
      .from('budget_entries')
      .select('*')
      .eq('type', 'income')
      .order('date_created', { ascending: false });

    if (error) throw error;
    return { data, error: null };
  } catch (error) {
    console.error('Error fetching income entries:', error);
    return { data: null, error };
  }
};

// Fetch only expense entries
export const getExpenseEntries = async () => {
  try {
    const { data, error } = await supabase
      .from('budget_entries')
      .select('*')
      .eq('type', 'expense')
      .order('date_created', { ascending: false });

    if (error) throw error;
    return { data, error: null };
  } catch (error) {
    console.error('Error fetching expense entries:', error);
    return { data: null, error };
  }
};

// Add a new entry
export const addEntry = async (entry) => {
  try {
    const { data, error } = await supabase
      .from('budget_entries')
      .insert([
        {
          type: entry.type,
          amount: entry.amount,
          description: entry.description,
          category: entry.category
          // date_created will be auto-generated by Supabase
        }
      ])
      .select();

    if (error) throw error;
    return { data, error: null };
  } catch (error) {
    console.error('Error adding entry:', error);
    return { data: null, error };
  }
};

// Delete an entry
export const deleteEntry = async (id) => {
  try {
    const { data, error } = await supabase
      .from('budget_entries')
      .delete()
      .eq('id', id)
      .select();

    if (error) throw error;
    
    // Check if any row was actually deleted
    if (data && data.length === 0) {
      console.warn('No entry found with ID:', id);
      return { error: { message: 'Entry not found or already deleted' } };
    }

    return { error: null };
  } catch (error) {
    console.error('Error deleting entry:', error);
    return { error };
  }
};

// Update an entry
export const updateEntry = async (id, updates) => {
  try {
    const { data, error } = await supabase
      .from('budget_entries')
      .update(updates)
      .eq('id', id)
      .select();

    if (error) throw error;
    return { data, error: null };
  } catch (error) {
    console.error('Error updating entry:', error);
    return { data: null, error };
  }
};

// Get summary statistics
export const getSummary = async () => {
  try {
    const { data, error } = await supabase
      .from('budget_entries')
      .select('type, amount');

    if (error) throw error;

    const summary = data.reduce(
      (acc, entry) => {
        if (entry.type === 'income') {
          acc.totalIncome += parseFloat(entry.amount);
        } else {
          acc.totalExpense += parseFloat(entry.amount);
        }
        return acc;
      },
      { totalIncome: 0, totalExpense: 0 }
    );

    summary.balance = summary.totalIncome - summary.totalExpense;

    return { data: summary, error: null };
  } catch (error) {
    console.error('Error fetching summary:', error);
    return { data: null, error };
  }
};
